from goalsetters.goalsetter import DCILGoalSetter
from goalsetters.goalsetter_mujoco import DCILGoalSetterMj
from goalsetters.goalsetter_variant import DCILGoalSetter_variant
from goalsetters.goalsetter_variant_mujoco import DCILGoalSetterMj_variant
# from goalsetters.goalsetter_variant_v2 import DCILGoalSetter_variant_v2
from goalsetters.goalsetter_variant_v2_mujoco import DCILGoalSetterMj_variant_v2
from goalsetters.goalsetter_variant_v3_mujoco import DCILGoalSetterMj_variant_v3
